Squashed 'custom-commands/' changes from 7fd6fbe..52d9d0a
52d9d0a Fixing dotdrop wrapper user parsing
1e2e8f0 Changing dotdrop command to have optional --user arg
cf943d9 Fixing paths in dotdrop wrapper script
983a857 Adding comments and input sanitization to dotdrop script
906d151 Removing useless custom binaries
5b505af Turning log-status to cron-log
1b8e8e3 Deleting useless script to pull from git repos - useing myrepos instead
7d35495 Adding log-status script
6dc506b Adding refresh-shell-cache command
0039baa Fixing binaries installing to root due to unset. Adding checks to avoid this in the future
599e61a Keepng exit code when recursively executing via sudo in install script

git-subtree-dir: custom-commands
git-subtree-split: 52d9d0af0fedef221c1f5de665af55aa9908f14e

diff --git a/user/dotdrop b/user/dotdrop
--- a/user/dotdrop
+++ b/user/dotdrop
@@ -2,6 +2,16 @@
 
 # This script is a convenience wrapper for dotdrop. It can be executed from
 # any dorectory, and will run the dotdrop command for user/root, or for both.
+#
+# Arguments:
+#   - --user USER: the user dotdrop will be executed for. Can be one of 'user',
+#       'root' or 'both'. Optional, defaults to 'user' for unprivileged users
+#        and to 'root' for root.
+#   - $@: dotdrop arguments.
+#
+# Environment:
+#   - $DOTFILES_HOME: the directory where Pipfile and dotdrop.sh are located.
+#                     Defaults to $HOME/Files/Programming/sys/dotfiles.
 
 #######################################
 # Variables
@@ -13,9 +23,51 @@ DOTFILES_HOME="${DOTFILES_HOME:-$HOME/Files/Programming/sys/dotfiles}"
 # Input processing
 #######################################
 
-WHO="$1"
-CMD="$2"
-shift 2
+WHO=''
+CMD=''
+ARGS=()
+
+CURR_ARG=''
+for ARG in "$@"; do
+    case "$CURR_ARG" in
+        'user')
+            WHO="$ARG"
+            CURR_ARG=''
+            continue
+            ;;
+    esac
+    case "$ARG" in
+        '--user'|'-U')
+            CURR_ARG='user'
+            ;;
+        *)
+            # Accorting to dotdrop syntax, the first argument must be the
+            # command.
+            [ -z "$CMD" ] && {
+                CMD="$ARG"
+                continue
+            }
+
+            # Relative paths need to be resolved before cd-ing into
+            # $DOTFILES_HOME, otherwise they become afterwards
+            [ -e "$ARG" ] && ARG="$(readlink -f "$ARG")"
+            ARGS+=("$ARG")
+            ;;
+    esac
+done
+
+case "$WHO" in
+    user|root|both)
+        ;;
+    '')
+        [ "$USER" = 'root' ] && WHO='root' || WHO='user'
+        ;;
+    *)
+        echo >&2 "Error: '$WHO' user given. Muse be one of 'user', 'root' or" \
+            "'both'"
+        exit 1
+        ;;
+esac
 
 #######################################
 # Executing dotdrop
@@ -27,13 +79,14 @@ cd $DOTFILES_HOME || exit
 
 case "$WHO" in
     user|both)
-        pipenv run bash dotdrop.sh "$CMD" -c 'config-user.yaml' "$@"
+        pipenv run bash dotdrop.sh "$CMD" -c 'config-user.yaml' "${ARGS[@]}"
         ;;
 esac
 
 case "$WHO" in
     root|both)
-        sudo pipenv run bash dotdrop.sh "$CMD" -c 'config-root.yaml' "$@"
+        sudo pipenv run bash dotdrop.sh "$CMD" -c 'config-root.yaml' \
+            "${ARGS[@]}"
         ;;
 esac
 
